default_language_version:
  python: python3.11
repos:
  - repo: local
    hooks:
      - id: ruff format
        name: ruff format
        language: system
        entry: ruff format
        types: [python]
      - id: isort
        name: isort
        language: system
        entry: isort
        args: ["--check", "--diff"]
        types: [python]
      - id: ruff
        name: ruff
        language: system
        entry: ruff
        args: ["--force-exclude"]
        types: [python]
      - id: mypy
        name: mypy
        language: system
        entry: mypy
        types: [python]