default_language_version:
  python: python3.11
repos:
  - repo: local
    hooks:
      - id: ruff format
        name: ruff format
        language: system
        entry: ruff format
        types: [python]
      - id: ruff check
        name: ruff
        language: system
        entry: ruff check --fix
        args: ["--force-exclude"]
        types: [python]
      - id: mypy
        name: mypy
        language: system
        entry: mypy
        types: [python]