# Generated by Django 5.1.7 on 2025-03-25 13:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhonebookGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.TextField(
                        max_length=50,
                        unique=True,
                        validators=[django.core.validators.MaxLengthValidator(50)],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PhonebookEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.TextField(
                        max_length=300,
                        validators=[django.core.validators.MaxLengthValidator(300)],
                    ),
                ),
                (
                    "city",
                    models.TextField(
                        max_length=50,
                        validators=[django.core.validators.MaxLengthValidator(50)],
                    ),
                ),
                (
                    "street",
                    models.TextField(
                        max_length=50,
                        validators=[django.core.validators.MaxLengthValidator(50)],
                    ),
                ),
                (
                    "postal_code",
                    models.TextField(
                        max_length=50,
                        validators=[django.core.validators.MaxLengthValidator(50)],
                    ),
                ),
                (
                    "country",
                    models.TextField(
                        max_length=50,
                        validators=[django.core.validators.MaxLengthValidator(50)],
                    ),
                ),
                (
                    "type",
                    models.TextField(choices=[("personal", "Personal"), ("enterprise", "Enterprise")]),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Group that phone entry belongs",
                        related_name="phonebook_entries",
                        to="phonebook.phonebookgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PhonebookNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.TextField(
                        max_length=20,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(20)],
                    ),
                ),
                (
                    "type",
                    models.TextField(choices=[("mobile", "Mobile"), ("landline", "Landline")]),
                ),
                (
                    "phonebook_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phonebook_number",
                        to="phonebook.phonebookentry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
