# Generated by Django 5.1.7 on 2025-03-28 07:18

import django.db.models.deletion
import model_utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phonebook", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhonebookEntryRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rate", models.PositiveIntegerField()),
                (
                    "phonebook_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phonebook_rating",
                        to="phonebook.phonebookentry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, model_utils.GrapheneModelMixin),
        ),
    ]
