# Generated by Django 5.1.7 on 2025-03-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phonebook", "0003_phonebookentryrating_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonebookentry",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
